---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    type: postgres
    author: skyda

spec:
  replicas: 1
  selector:
    matchLabels:
      type: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        type: postgres
        author: skyda
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: Admin1
            - name: POSTGRES_DB
              value: mydb
...
