---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    type: redis-deployment
    author: skyda

spec:
  replicas: 1
  selector:
    matchLabels:
      type: redis-deployment
  template:
    metadata:
      name: redis-pod
      labels:
        type: redis-deployment
    spec:
      containers:
        - name: redis
          image: redis
...