---
apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    type: resultapp-service
    author: skyda

spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: resultapp-deployment
    author: skyda
...