---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingApp-deployment
  labels:
    type: votingApp-deployment
    author: skyda

spec:
  replicas: 2
  selector:
    matchLabels:
      type: votingApp-deployment
  template:
    metadata:
      name: votingApp-pod
      labels:
        type: votingApp-deployment
        author: skyda
    spec:
      containers:
        - name: votingApp
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
...