---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerapp-deployment
  labels:
    type: workerapp
    author: skyda

spec:
  replicas: 1
  selector:
    matchLabels:
      type: workerapp
  template:
    metadata:
      name: workerapp-pod
      labels:
        type: workerapp
    spec:
      containers:
        - name: workerapp
          image: dockersamples/examplevotingapp_worker
